# Settings
# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "ko-KR"
title: "Powerticket's GitHub Blog"
title_separator: "|"
subtitle: "Version 1.0"
name: "Powerticket's GitHub Blog"
description: "Blog about **Python**"
url: "https://powerticket.github.io"
repository: "powerticket/powerticket.github.io"
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - /assets/js/your-custom-head-script.js
teaser: "/assets/images/nebula.jpg"
header:
  teaser: "/assets/images//assets/images/nebula.jpg"
logo: "/assets/images/JEON.jpg"
breadcrumbs: true  # disabled by default
words_per_minute: 200
defaults:
  # _posts
  - scope:
      path: "/_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
search: true
author:
  name     : "전원표"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "**Python** 공부중"
  location : "Seoul, Korea"
    links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/powerticket"
timezone: Asia/Seoul